force-app/main/default/objects/Action__e/Action__e.object-meta.xml
<CustomObject>
    <description>Centralized Platform to handle all actions on the platform</description>
    <label>Action</label>
    <pluralLabel>Actions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Action__e/fields/JSON_Body__c.field-meta.xml
<CustomField>
    <fullName>JSON_Body__c</fullName>
    <description>JSON body representing an EventBody apex object</description>
    <label>JSON Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/PlatformActionTriggerLogic.cls
/******************************************************************************
Author:Ryan O'Sullivan
Company:CloudKettle
Test Class(s):PlatfromCentralizerUnitTest
Description:Trigger logic used for Action__e central handler trigger. 

History:
 Date:2021-02-24
 By:Ryan O'Sullivan
 Action:Created
******************************************************************************/
public class PlatformActionTriggerLogic extends BasePlatformTriggerLogic{
    List<SObject> workerEvents = new List<SObject>();
    public PlatformActionTriggerLogic(String eventDevName) {
        super(eventDevName);
    }

    override protected void loopLogic(SObject event){
        // Create list of workers here
        workerEvents.add(PlatformWorkerRouter.assignWorker((String)event.get('JSON_Body__c')));
    }

    override protected void postLoopLogic(){
        // Execute list of workers here
        Eventbus.publish(workerEvents);
    }

}