force-app/main/default/objects/Platform_Action_Settings__mdt/Platform_Action_Settings__mdt.object-meta.xml
<CustomObject>
    <description>Used to control configuration options for the platform action centralized Platform Event model.

The platform action handler will only grab the first setting record listed as active. If there are more active they will be ignored until the one prior (via label alphabetical order) is inactived.</description>
    <label>Platform Action Setting</label>
    <pluralLabel>Platform Action Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Platform_Action_Settings__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Defines if this setting is active and should be used in handler. Note only the first active (first defined by alphabetical order of label name) is used to determine runtime settings. Although there can be multiple active settings only one is used. This logic can be used to hot swap settings if need be.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Platform_Action_Settings__mdt/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Defines the number of platform action events to be run in a single execution context</description>
    <inlineHelpText>Range from 1-2000</inlineHelpText>
    <label>Batch Size</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Platform_Action_Settings__mdt/fields/Max_Retries__c.field-meta.xml
<CustomField>
    <fullName>Max_Retries__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Defines the number of times an event will retry itself if there is an error. Note there is a max of 10 (including initial run) that once hit will result in the trigger being deactivated https://developer.salesforce.com/docs/atlas.en-us.platform_events.meta/platform_events/platform_events_subscribe_apex_refire.htm</description>
    <inlineHelpText>range from 0 - 9</inlineHelpText>
    <label>Max Retries</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Platform_Callables__mdt/Platform_Callables__mdt.object-meta.xml
<CustomObject>
    <description>A list of all callable actions to give the ability to turn off a given action from functioning</description>
    <label>Platform Callable</label>
    <pluralLabel>Platform Callables</pluralLabel>
</CustomObject>

force-app/main/default/objects/Platform_Callables__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Defines if this callable action is active or not</description>
    <inlineHelpText>Enable/Disable Apex Class</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PlatformActionUtil.cls
/******************************************************************************
Author:Ryan O'Sullivan
Company:CloudKettle
Test Class(s):PlatfromCentralizerUnitTest
Description:Utility class to hold common methods for the Platform Action
Framework

History:
 Date:2021-02-15
 By:Ryan O'Sullivan
 Action:Created
******************************************************************************/
public class PlatformActionUtil {
    private final static Integer OVER_RIDE_DEFAULT_BATCH_SIZE = 1;
    private final static Integer OVER_RIDE_DEFAULT_RETRY_SIZE = 0;
    private static Platform_Action_Settings__mdt settings;
    @TestVisible private static Map<String,List<String>> activeCallables;
    @TestVisible private static Boolean testCalled = false;
    
    /*************************Method**********************************
    @author:Ryan O'Sullivan
    @since:2021-02-15
    Description:Returns Batch Size setting from custom metadata
    Platform_Action_Settings__mdt 
    
    @return Integer representing batch size config option
    *****************************************************************/
    static public Integer getBatchSizeSetting(){
        return (Integer)getSettings().Batch_Size__c;
    }

    /*************************Method**********************************
    @author:Ryan O'Sullivan
    @since:2021-02-15
    Description:Returns a Max Retry size setting from custom metadata
    Platform_Action_Settings__mdt
    
    @return Integer representing max retry config option
    *****************************************************************/
    static public Integer getMaxRetrySetting(){
        return (Integer)getSettings().Max_Retries__c;
    }

    /*************************Method**********************************
    @author:Ryan O'Sullivan
    @since:2021-03-03
    Description:Gets a list of callable actions that are defined in
    Platform_Callables__mdt. All active callable classes should be
    defined here in order to run
    
    @return List of Strings represnting lower case class names
    *****************************************************************/
    static public Map<String,List<String>> getActiveCallables(){
        if(activeCallables == null){
            activeCallables = new Map<String,List<String>>();
            for(Platform_Callables__mdt callable : [SELECT NamespacePrefix, label FROM Platform_Callables__mdt WHERE active__c = true]){
                String lowercaseLabel = callable.label.toLowerCase();
                if(activeCallables.containsKey(callable.NamespacePrefix)){
                    activeCallables.get(callable.NamespacePrefix).add(lowercaseLabel);
                } else {
                    activeCallables.put(callable.NamespacePrefix,new List<String>{lowercaseLabel});
                }
            }
        }
        return activeCallables;
    }

    static private Platform_Action_Settings__mdt getSettings(){
        if(settings == null){
            // Query settings from Custom Metadata if not cached
            Platform_Action_Settings__mdt[] settingsQuery = [Select Batch_Size__c,Max_Retries__c from Platform_Action_Settings__mdt where Active__c = true order by label asc limit 1];
            if(settingsQuery.isempty()){
                // Create override defaults if nothing in custom metadata
                settings = new Platform_Action_Settings__mdt(
                    Batch_Size__c = OVER_RIDE_DEFAULT_BATCH_SIZE,
                    Max_Retries__c = OVER_RIDE_DEFAULT_RETRY_SIZE
                );
            } else {
                settings = settingsQuery[0]; // Return first from list
            }
        }
        return settings;
    }

    // This class is just used for the PlatformCentralizerUnitTest
    public class testableAction implements Callable {
        public Object call(String action, Map<String, Object> args) {
            testCalled = true;
            return null;
        }
    }
}