force-app/main/default/objects/Platform_Action_Worker__mdt/Platform_Action_Worker__mdt.object-meta.xml
<CustomObject>
    <description>Maps platform actions from the centralized handler to given workers described in this list. Each record in this metadata represents an associated platform event with a handler that will get executed on</description>
    <label>Platform Action Worker</label>
    <pluralLabel>Platform Action Workers</pluralLabel>
</CustomObject>

force-app/main/default/objects/Platform_Action_Worker__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Used to determine if this worker is active or not. Only active workers will be used to send work to</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Platform_Action_Worker__mdt/fields/Body_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Body_Field_Name__c</fullName>
    <description>The API name of the field that will map the body message of the platform event. Must be a long text field</description>
    <inlineHelpText>API name of JSON body field</inlineHelpText>
    <label>Body Field Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Action_Worker__mdt/fields/Platform_Event_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Platform_Event_Api_Name__c</fullName>
    <description>The name of the platform event representing a worker for the centralized platform action handler</description>
    <label>Platform Event Api Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Platform_Callables__mdt/Platform_Callables__mdt.object-meta.xml
<CustomObject>
    <description>A list of all callable actions to give the ability to turn off a given action from functioning</description>
    <label>Platform Callable</label>
    <pluralLabel>Platform Callables</pluralLabel>
</CustomObject>

force-app/main/default/objects/Platform_Callables__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Defines if this callable action is active or not</description>
    <inlineHelpText>Enable/Disable Apex Class</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PlatformWorkerTriggerLogic.cls
/******************************************************************************
Author:Ryan O'Sullivan
Company:CloudKettle
Test Class(s):PlatfromCentralizerUnitTest
Description:Logic used in each worker class, parses the action defined in 
the json body for each event AND executes to corresponding
 APEX class 
 

History:
 Date:2021-02-24
 By:Ryan O'Sullivan
 Action:Created
******************************************************************************/
public class PlatformWorkerTriggerLogic extends BasePlatformTriggerLogic{
    private String workerBodyFieldName;
    private List<String> activeCallables;
    private Set<String> invalidClassList = new Set<String>();
    private Set<String> inactiveClassList = new Set<String>();

    public PlatformWorkerTriggerLogic(String eventDevName){
        super(eventDevName);
    }

    // Code that happens for each loop of the given trigger object (i.e. creating list)
    override protected void loopLogic(SObject event){
        List<CallableAction> eventActions = (List<CallableAction>)JSON.deserializeStrict((String)event.get(getWorkerBodyName()),List<CallableAction>.class);
        for(CallableAction action : eventActions){
            if(checkActiveClass(action.className)){
                callAction(action);
            } else {
                // Debug list for post
                inactiveClassList.add(action.className);
            }
        }
    }

    // Code that happens after looping through each trigger object (i.e. processing list)
    override protected void postLoopLogic(){
        if(!inactiveClassList.isEmpty()){
            for(String inactiveClass : inactiveClassList){
                System.debug('🔧🔧🔧 ' + inactiveClass + ' is either inactive in Platform_Callables__mdt or not included and has been skipped');
            }
        }

        if(!invalidClassList.isEmpty()){
            for(String invalidClass : invalidClassList){
                System.debug('❌❌❌ ' + invalidClass + ' does not implement the interface Callable and was unable to run');
            }
        }
    }
    
    private String getWorkerBodyName(){
        if(workerBodyFieldName == null){
            this.workerBodyFieldName = [SELECT Body_Field_Name__c 
                                        FROM Platform_Action_Worker__mdt 
                                        WHERE active__c = true 
                                        AND Platform_Event_Api_Name__c =: this.SobjectApiName 
                                        LIMIT 1]
                                        ?.Body_Field_Name__c;
        }
        return this.workerBodyFieldName;
    }

    private Boolean checkActiveClass(String className){
        return PlatformActionUtil.getActiveCallables().contains(className?.toLowerCase());
    }

    private void callAction(CallableAction action){
        Type callableClass = Type.forName(action.nameSpace,action.className);
        if(Callable.class.isAssignableFrom(callableClass)){
            // Class is a callable
            ((Callable)callableClass.newInstance()).call(action.action, action.args);
        } else {
            // Debug list for post
            invalidClassList.add(action.className);
        }
    }

}